image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - pip install docker-auto-labels

build:
  stage: build
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - TAG=latest sh ./scripts/build-push.sh
    - TAG="$CI_COMMIT_REF_NAME" sh ./scripts/build-push.sh

deploy:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - master
  variables:
    DOCKER_HOST: $DOMAIN_HOST
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - >
      DOMAIN="$DOMAIN"
      PATH_PREFIX="$PATH_PREFIX"
      TRAEFIK_TAG="$TRAEFIK_TAG"
      STACK_NAME="$STACK_NAME"
      TAG="$CI_COMMIT_REF_NAME"
      sh ./scripts/deploy.sh
  environment:
    name: master
    url: $DOMAIN


