version: '3.3'
services:
  app:
    deploy:
      replicas: 1
  mysql:
    deploy:
      replicas: 1
  migration:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
