version: '3.3'
services:
  app:
    deploy:
      labels:
        - traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:${PATH_PREFIX}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_TAG}
