version: '3.3'
services:
  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
  app:
    command: 'rr serve -v -d -c /app/.rr.local.yml'
