version: '3.3'
services:
  proxy:
    labels:
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.enable=true
      - traefik.port=80
  app:
    labels:
      - traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:/fiaspoly
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}
