version: '3.3'
services:
  app:
    deploy:
      labels:
        - traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:${PATH_PREFIX}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_TAG}
        - traefik.docker.network=${TRAEFIK_TAG}
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints= https

